version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: procurement-postgres
    environment:
      POSTGRES_DB: procurement_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: procurement-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: procurement-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  ml-service:
    build: ./ml-service
    container_name: procurement-ml
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  api-gateway:
    build: ./backend-gateway
    container_name: procurement-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/procurement_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - redis
      - rabbitmq

  expense-service:
    build: ./expense-service
    container_name: procurement-expense
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/procurement_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      ML_SERVICE_URL: http://ml-service:5000
    depends_on:
      - postgres
      - redis
      - rabbitmq
      - ml-service

  procurement-service:
    build: ./procurement-service
    container_name: procurement-proc
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/procurement_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - postgres
      - redis
      - rabbitmq

  frontend:
    build: ./frontend
    container_name: procurement-frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
